cart/urls.py
from django.urls import path
from .views import CartListView, AddToCartView, ClearCartView, RemoveFromCartView, payment_view

urlpatterns = [
    path('', CartListView.as_view(), name='cart_detail'),
    path('add/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),  # Captures product ID as 'pk'
    path('clear/', ClearCartView.as_view(), name='clear_cart'),
    path('remove/<str:product_id>/', RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('payment', payment_view, name='payment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='/products/home'), name='root-redirect-to-products'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/products/', null=True, blank=True)
    liked_by = models.ManyToManyField(get_user_model(), related_name='liked_products', blank=True)
    stock = models.PositiveBigIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name

base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300..700&family=Oswald:wght@200..700&display=swap" rel="stylesheet">
    <title>{% block title %}Coder Store{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cyborg/bootstrap.min.css" integrity="sha384-nEnU7Ae+3lD52AK+RGNzgieBWMnEfgTbRHIwEvp1XXPdqdO6uLTd/NwXbzboqjc2" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% block css %}
    <link rel="stylesheet" href="{% static 'media/css/base.css' %}">
    {% endblock %}
</head>
<body>
    

    {% include "navbar.html" %}

    {% block content %}
       
    {% if user.is_authenticated %}
        <a href="{% url 'favorite_products' %}" class="nav-link">My Favorites</a>
    {% endif %}
        
    {% endblock %}
    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    <footer>
        <div class="footer-logo">
            <a href="https://sdgku.edu/">
                <img src="{% static 'media/images/logo/logosdgku.png' %}">
            </a>
        </div>
        <div class="footer-content">
            <div class="social-media">
                <a href="https://facebook.com" target="_blank"><i class="fa-brands fa-facebook-f"></i></a>
                <a href="https://twitter.com" target="_blank"><i class="fa-brands fa-x-twitter"></i></a>
                <a href="https://instagram.com" target="_blank"><i class="fa-brands fa-instagram"></i></a>
            </div>
                <small>&copy; 2024 <b>SDGKU</b> - All Rights Reserved.</small>
        </div>
    </footer>
</body>
</html>

base/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home page{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet">    
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'media/css/home.css' %}">
    {% endblock %}
</head>
<body>
    <h1>Gamer's Favorites.<span style="color:rgb(113, 113, 113)"> Best Sellers</span></h1>
    <main class="container">
        <div class="slider">
            <div class="slides">

                <div class="slide">
                    <img src="{% static 'media/images/products/dronemavic2.png' %}"> 
                </div>
                
                <div class="slide">
                    <img src="{% static 'media/images/products/lenovo-legionGo.png' %}">
                </div>
                
                <div class="slide">
                    <img src="{% static 'media/images/products/ssd-casergb.png' %}">
                </div>
                
                <div class="slide">
                    <img src="{% static 'media/images/products/msi-claw.png' %}">
                </div>
                
                <div class="slide">
                    <img src="{% static 'media/images/products/meta-quest-.png' %}">
                </div>

                <div class="slide">
                    <img src="{% static 'media/images/products/valve-steam.png' %}">
                </div>

                <div class="slide">
                    <img src="{% static 'media/images/products/sony-vr2.png' %}">
                </div>
            </div>
            
            <div class="slider-controls">
                <button class="slider-button" onclick="prevSlide()">&#10094;</button>
                <button class="slider-button" onclick="nextSlide()">&#10095;</button>
            </div>
        </div>

        <div class="banner-text">
            Save $25 with your Golden Membership when you spend $250 In Store Or Online & Pick up in Store*
        </div>

        <div class="video-section">
            <video autoplay muted loop width="100%" controls>
                <source src="{% static 'media/videos/Phantom-Blade-Zero.mp4' %}" type="video/mp4">
            </video>
        </div>

        <div class="card">
            <img src="{% static 'media/images/products/bannerassasins.png' %}">
        </div>

        <div class="grid-container">

            <div class="card">
                <a href="https://rewards.msi.com/">
                    <img src="{% static 'media/images/logo/msi-log.png' %}">
                </a>
            </div>
            <div class="card">
                <a href="https://www.nintendo.com/us/switch/online/nintendo-switch-online/#nso-compare-table">
                    <img src="{% static 'media/images/logo/nintendo-online.png' %}">
                </a>
            </div>
            <div class="card">
                <a href="https://www.playstation.com/en-us/ps-plus/#subscriptions">
                    <img src="{% static 'media/images/logo/ps-log.png' %}">
                </a>
            </div>
            <div class="card">
                <a href="https://www.nvidia.com/en-us/geforce-now/memberships/">
                    <img src="{% static 'media/images/logo/nvidia.png' %}">
                </a>    
            </div>
            <div class="card">
                <a href="https://www.xbox.com/en-US/live/gold">
                    <img src="{% static 'media/images/logo/xbox.png' %}">
                </a>
            </div>
        </div>

        <div class="card">
            <a href="http://127.0.0.1:8000/products/34/">
                <img src="{% static 'media/images/products/NBA.png' %}">
            </a>
        </div>

        <h2 class="h2-gold">Membership Benefits & Free Shipping</h2>

    </main>
    <script src="{% static 'js/home.js' %}"></script>
</body>
</html>
{% endblock %}
    

base/templates/navbar.html
{% load static %}
{%block css %}
    <link rel="stylesheet" href="{% static '/media/css/navbar.css' %}">
{% endblock %}
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}  ">CoderStore</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white" class="bi bi-list" width="24" height="24">
                <path d="M3 6h18v2H3zm0 5h18v2H3zm0 5h18v2H3z"/>
            </svg>
    
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <li class="nav-item px-3">
                    <a class="nav-link active " aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item px-3">
                    <a class="nav-link px-3" href="{% url 'product_list' %}">Catalog</a>
                </li>
                <!--<li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle px-3" href="#" id="membershipDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Members
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="membershipDropdown">
                        <li><a class="dropdown-item" href="#">Golden Membership <i class="fa-solid fa-star"></i></a></li>
                        <li><a class="dropdown-item" href="#">Silver Membership <i class="fa-solid fa-star-half"></i></a></li>
                        <li><a class="dropdown-item" href="{% url 'login' %}">Not a Memeber yet? Sign up!</a></li>
                    </ul>
                </li>-->
                    <li class="nav-item">
                        <a class="nav-link px-3" href="{% url 'contact_us' %}">Contact</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link px-3" href="{% url 'favorite_products' %}">Your favorites</a>
                    </li>
                    {% endif %}
                </li>
            </ul>
                <form method="get" action="{% url 'search_products' %}">
                    <input type="text" placeholder="Search" name="query">
                    <button class="submit btn btn-dark">Search</button>
                </form> 
                
            {% if user.is_authenticated %}
                <form class="d-flex" role="search" action="{% url 'cart_detail' %}" method="get">
                    <button class="btn btn-outline-light" type="submit">
                        <i class="fa-solid fa-cart-shopping cart-icon"></i>
                    </button>
                </form>
            {% else %}
                <form class="d-flex" role="search" action="{% url 'login' %}" method="get">
                    <button class="btn btn-outline-light" type="submit">
                        <i class="fa-solid fa-cart-shopping cart-icon"></i>
                    </button>
                </form>
            {% endif %}
            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-regular fa-id-badge cart-icon"></i>
                </button>
                <ul class="dropdown-menu custom-dropdown-menu" aria-labelledby="userDropdown">
                    {% if user.is_authenticated %}
                    <li>
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <span class="dropdown-item-text">{{ user.first_name }} {{user.last_name}}</span>
                            <span class="dropdown-item-text">{{ user.email }}</span>
                            <button type="submit" class="btn btn-link">Logout <i class="fa-solid fa-arrow-right-from-bracket"></i></button>
                        </form>
                    </li>
                    {% else %}
                        <li><a class="dropdown-item text-center" href="{% url 'login' %}">Login <i class="fa-solid fa-arrow-right-to-bracket"></i></a></li>
                        <li><a class="dropdown-item text-center" href="{% url 'signup' %}">Create an account  <i class="fa-solid fa-user-plus"></i></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>